# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3faef261-8bc8-440b-a65d-c781ba07804e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4277-FC10";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enable bluetooth
  hardware.bluetooth.enable = true; # enables support for Bluetooth
  hardware.bluetooth.powerOnBoot = true; # powers up the default Bluetooth controller on boot

  # Enable NFS Shares
  fileSystems."/mnt/TrueNAS/Backup" =
    { device = "192.168.2.110:/mnt/FastPool/Backup";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/Documents" =
    { device = "192.168.2.110:/mnt/FastPool/Documents";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/Downloads" =
    { device = "192.168.2.110:/mnt/FastPool/Downloads";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/Elsa" =
    { device = "192.168.2.110:/mnt/FastPool/Elsa";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/Etienne" =
    { device = "192.168.2.110:/mnt/FastPool/Etienne";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/Gaming" =
    { device = "192.168.2.110:/mnt/FastPool/Gaming";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/IT" =
    { device = "192.168.2.110:/mnt/FastPool/IT";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/Mateo" =
    { device = "192.168.2.110:/mnt/FastPool/Mateo";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/Music" =
    { device = "192.168.2.110:/mnt/FastPool/Music";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/Photos" =
    { device = "192.168.2.110:/mnt/FastPool/Photos";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/Uploads" =
    { device = "192.168.2.110:/mnt/FastPool/Uploads";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

  fileSystems."/mnt/TrueNAS/Videos" =
    { device = "192.168.2.110:/mnt/FastPool/Videos";
      fsType = "nfs";
      options = [ "defaults" "timeo=900" "retrans=5" "_netdev" ];
    };

# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
